on:
  push:
    branches:
      - main
name: 🚀 Deploy website To Production
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "dodolanobattani.com"
        username: "u297041661"
        password: "Rahasia97@"
        server-dir: "/domains/dodolanobattani.com/public_html/internal/"
